// <auto-generated />
using System;
using EnerGov.WebApi.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnerGov.WebApi.Migrations
{
    [DbContext(typeof(EF_DataContext))]
    partial class EFDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("EnerGov.Core.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.ToTable("employee");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            FirstName = "Jefferey",
                            LastName = "Wells"
                        },
                        new
                        {
                            EmployeeId = 2,
                            FirstName = "Vector",
                            LastName = "Atkins",
                            ManagerId = 1
                        },
                        new
                        {
                            EmployeeId = 3,
                            FirstName = "Kelli",
                            LastName = "Hamilton",
                            ManagerId = 1
                        },
                        new
                        {
                            EmployeeId = 4,
                            FirstName = "Adam",
                            LastName = "Brown",
                            ManagerId = 2
                        },
                        new
                        {
                            EmployeeId = 5,
                            FirstName = "Lois",
                            LastName = "Martinez",
                            ManagerId = 3
                        },
                        new
                        {
                            EmployeeId = 6,
                            FirstName = "Brian",
                            LastName = "Cruz",
                            ManagerId = 2
                        },
                        new
                        {
                            EmployeeId = 7,
                            FirstName = "Michael",
                            LastName = "Lind",
                            ManagerId = 3
                        },
                        new
                        {
                            EmployeeId = 8,
                            FirstName = "Kristen",
                            LastName = "Floyd",
                            ManagerId = 2
                        },
                        new
                        {
                            EmployeeId = 9,
                            FirstName = "Eric",
                            LastName = "Bay",
                            ManagerId = 3
                        },
                        new
                        {
                            EmployeeId = 10,
                            FirstName = "Brandon",
                            LastName = "Young",
                            ManagerId = 3
                        });
                });

            modelBuilder.Entity("EnerGov.Core.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("EmployeeRoleId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeeRoleId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("employeerole");

                    b.HasData(
                        new
                        {
                            EmployeeRoleId = 1,
                            EmployeeId = 1,
                            Role = 1,
                            RoleId = 1
                        },
                        new
                        {
                            EmployeeRoleId = 2,
                            EmployeeId = 2,
                            Role = 1,
                            RoleId = 1
                        },
                        new
                        {
                            EmployeeRoleId = 3,
                            EmployeeId = 3,
                            Role = 1,
                            RoleId = 1
                        },
                        new
                        {
                            EmployeeRoleId = 4,
                            EmployeeId = 4,
                            Role = 3,
                            RoleId = 3
                        },
                        new
                        {
                            EmployeeRoleId = 5,
                            EmployeeId = 4,
                            Role = 2,
                            RoleId = 2
                        },
                        new
                        {
                            EmployeeRoleId = 6,
                            EmployeeId = 5,
                            Role = 2,
                            RoleId = 2
                        },
                        new
                        {
                            EmployeeRoleId = 7,
                            EmployeeId = 6,
                            Role = 4,
                            RoleId = 4
                        },
                        new
                        {
                            EmployeeRoleId = 8,
                            EmployeeId = 7,
                            Role = 5,
                            RoleId = 5
                        },
                        new
                        {
                            EmployeeRoleId = 9,
                            EmployeeId = 8,
                            Role = 5,
                            RoleId = 5
                        },
                        new
                        {
                            EmployeeRoleId = 10,
                            EmployeeId = 8,
                            Role = 6,
                            RoleId = 6
                        },
                        new
                        {
                            EmployeeRoleId = 11,
                            EmployeeId = 9,
                            Role = 3,
                            RoleId = 3
                        },
                        new
                        {
                            EmployeeRoleId = 12,
                            EmployeeId = 9,
                            Role = 6,
                            RoleId = 6
                        },
                        new
                        {
                            EmployeeRoleId = 13,
                            EmployeeId = 10,
                            Role = 4,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("EnerGov.Core.Employee", b =>
                {
                    b.HasOne("EnerGov.Core.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EnerGov.Core.EmployeeRole", b =>
                {
                    b.HasOne("EnerGov.Core.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EnerGov.Core.Employee", b =>
                {
                    b.Navigation("EmployeeRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
